# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-25 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.CharField(max_length=10)),
                ('ra', models.CharField(max_length=15)),
                ('dec', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SkyObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sky.Direction')),
            ],
        ),
    ]
